name: CD

on:
  push:
    branches: ['master']

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: 'master'
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.x'
          elixir-version: '1.9.4'
      - name: Publish package on hex.pm
        run: |
          mix deps.get
          mix hex.config api_key ${{ secrets.HEX_API_KEY }}  
          mix hex.publish --yes
